# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hash_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HashCatWindow(object):
    def setupUi(self, HashCatWindow):
        HashCatWindow.setObjectName("HashCatWindow")
        HashCatWindow.resize(551, 538)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        HashCatWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(HashCatWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_hashcat = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_hashcat.setGeometry(QtCore.QRect(140, 40, 221, 51))
        self.pushButton_hashcat.setObjectName("pushButton_hashcat")
        self.pushButton_quit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_quit.setGeometry(QtCore.QRect(170, 400, 131, 51))
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.textEdit_options = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_options.setGeometry(QtCore.QRect(60, 140, 441, 41))
        self.textEdit_options.setToolTip("")
        self.textEdit_options.setStatusTip("")
        self.textEdit_options.setObjectName("textEdit_options")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 110, 151, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 190, 251, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 270, 151, 31))
        self.label_3.setObjectName("label_3")
        self.pushButton_browse_hashfile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_browse_hashfile.setGeometry(QtCore.QRect(60, 220, 111, 51))
        self.pushButton_browse_hashfile.setObjectName("pushButton_browse_hashfile")
        self.pushButton_browse_wordlist = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_browse_wordlist.setGeometry(QtCore.QRect(60, 300, 111, 51))
        self.pushButton_browse_wordlist.setObjectName("pushButton_browse_wordlist")
        self.textBrowser_hashfile = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_hashfile.setGeometry(QtCore.QRect(180, 220, 321, 51))
        self.textBrowser_hashfile.setObjectName("textBrowser_hashfile")
        self.textBrowser_wordlist = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_wordlist.setGeometry(QtCore.QRect(180, 300, 321, 51))
        self.textBrowser_wordlist.setObjectName("textBrowser_wordlist")
        HashCatWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HashCatWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 551, 29))
        self.menubar.setObjectName("menubar")
        HashCatWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HashCatWindow)
        self.statusbar.setObjectName("statusbar")
        HashCatWindow.setStatusBar(self.statusbar)

        self.retranslateUi(HashCatWindow)
        self.pushButton_quit.clicked.connect(HashCatWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(HashCatWindow)

    def retranslateUi(self, HashCatWindow):
        _translate = QtCore.QCoreApplication.translate
        HashCatWindow.setWindowTitle(_translate("HashCatWindow", "MainWindow"))
        self.pushButton_hashcat.setText(_translate("HashCatWindow", "Run HashCat"))
        self.pushButton_quit.setText(_translate("HashCatWindow", "quit"))
        self.label.setText(_translate("HashCatWindow", "options:"))
        self.label_2.setText(_translate("HashCatWindow", "hash file (txt):"))
        self.label_3.setText(_translate("HashCatWindow", "wordlist (txt):"))
        self.pushButton_browse_hashfile.setText(_translate("HashCatWindow", "Browse"))
        self.pushButton_browse_wordlist.setText(_translate("HashCatWindow", "Browse"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HashCatWindow = QtWidgets.QMainWindow()
    ui = Ui_HashCatWindow()
    ui.setupUi(HashCatWindow)
    HashCatWindow.show()
    sys.exit(app.exec_())
